feature/hip-12-add-GitHub-ci
yribeiro/hippo pull request #10
Opened 2022-02-07 22:23 UTC by yribeiro

2022-02-21 09:17 UTC, mateimol requested changes
Change comment line (line 45) in run_docs.yml to match the actual file actions.

2022-02-21 09:17 UTC, mateimol commented on .github/workflows/run_docs.yml
> +    # Runs precommit using the repo config file
shouldn't this line say that it checks or builds docs? instead of saying it runs the pre-commit ?

2022-02-22 20:56 UTC, yribeiro commented on .github/workflows/run_docs.yml
> +    # Runs precommit using the repo config file
yup, you're right. Updated.

2022-02-23 20:15 UTC, mateimol approved these changes
All good.

2022-02-23 21:23 UTC, merged